//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A.H.M.O._2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MontoEspecialidad
    {
        public int IdMe { get; set; }
        public int IdPrev { get; set; }
        public int IdE { get; set; }
        public Nullable<int> Monto { get; set; }
        public int Abono { get; set; }
        public int ValorBono { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
        public virtual Prevision Prevision { get; set; }
    }
}
