//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A.H.M.O._2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int IdR { get; set; }
        public int IdU { get; set; }
        public int IdP { get; set; }
        public Nullable<int> IdA { get; set; }
    
        public virtual Agenda Agenda { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
